"""
YouTube Shorts service — resumable upload via the YouTube Data API v3.

Flow:
  1. Exchange the refresh token for a fresh access token.
  2. Initiate a resumable upload with snippet + status metadata.
  3. Stream the video binary to the resumable URI.

Ref: https://developers.google.com/youtube/v3/guides/using_resumable_upload_protocol
"""

import json
import os

import requests

from app.config import settings
from app.utils.logger import get_logger

logger = get_logger(__name__)

TOKEN_URL = "https://oauth2.googleapis.com/token"
UPLOAD_URL = "https://www.googleapis.com/upload/youtube/v3/videos"


def _get_access_token() -> str:
    """Exchange the stored refresh token for a short-lived access token."""
    resp = requests.post(
        TOKEN_URL,
        data={
            "client_id": settings.YOUTUBE_CLIENT_ID,
            "client_secret": settings.YOUTUBE_CLIENT_SECRET,
            "refresh_token": settings.YOUTUBE_REFRESH_TOKEN,
            "grant_type": "refresh_token",
        },
        timeout=15,
    )
    resp.raise_for_status()
    token: str = resp.json()["access_token"]
    return token


def _initiate_upload(
    access_token: str,
    title: str,
    description: str,
) -> str:
    """Start a resumable upload session and return the upload URI."""
    metadata = {
        "snippet": {
            "title": title,
            "description": description,
            "tags": ["AI", "AI Tools", "Shorts"],
            "categoryId": "28",  # Science & Technology
        },
        "status": {
            "privacyStatus": "public",
            "selfDeclaredMadeForKids": False,
        },
    }

    resp = requests.post(
        UPLOAD_URL,
        params={
            "uploadType": "resumable",
            "part": "snippet,status",
        },
        headers={
            "Authorization": f"Bearer {access_token}",
            "Content-Type": "application/json; charset=UTF-8",
            "X-Upload-Content-Type": "video/mp4",
        },
        data=json.dumps(metadata),
        timeout=30,
    )
    resp.raise_for_status()

    upload_uri: str = resp.headers["Location"]
    return upload_uri


def _upload_video(upload_uri: str, video_path: str, access_token: str) -> None:
    """Stream the video file to the resumable upload URI."""
    file_size = os.path.getsize(video_path)

    with open(video_path, "rb") as fh:
        resp = requests.put(
            upload_uri,
            data=fh,
            headers={
                "Authorization": f"Bearer {access_token}",
                "Content-Type": "video/mp4",
                "Content-Length": str(file_size),
            },
            timeout=600,
        )
    resp.raise_for_status()
    video_id = resp.json().get("id", "unknown")
    logger.info("YouTube: video uploaded — https://youtube.com/shorts/%s", video_id)


def post_to_youtube(title: str, description: str, video_path: str) -> bool:
    """Upload a video as a YouTube Short.

    Args:
        title: Video title (typically the tool name).
        description: SEO-friendly description generated by the caption service.
        video_path: Local path to the MP4 file.

    Returns:
        ``True`` on success, ``False`` on failure.
    """
    try:
        logger.info("YouTube: obtaining access token...")
        access_token = _get_access_token()

        # Append #Shorts to the title to signal YouTube
        short_title = f"{title} #Shorts" if "#Shorts" not in title else title

        logger.info("YouTube: initiating resumable upload...")
        upload_uri = _initiate_upload(access_token, short_title, description)

        logger.info("YouTube: uploading video...")
        _upload_video(upload_uri, video_path, access_token)

        logger.info("YouTube: upload complete.")
        return True

    except requests.RequestException as exc:
        # Log the full response body when available — invaluable for debugging
        body = ""
        if hasattr(exc, "response") and exc.response is not None:
            try:
                body = exc.response.text
            except Exception:
                body = "(could not read response body)"
        logger.error("YouTube posting failed: %s | Response: %s", exc, body)
        return False
